[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_ctf = "2X7zzfhm3jT1RJexfy4N2Z5bfZCzHULizY8px16YPmkc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/agathokako/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
